const songs = [
    { name: 'Bohemian Rhapsody', artist: ['Queen'], genres: ['Rock'], duration: '5:55' },
    { name: 'Jolene', artist: ['Dolly Parton'], genres: ['Country'], duration: '2:42' },
    { name: 'Blinding Lights', artist: ['The Weeknd'], genres: ['Pop', 'R&B'], duration: '3:20' },
    { name: 'Lose Yourself', artist: ['Eminem'], genres: ['Hip-Hop'], duration: '5:26' },
    { name: 'Take Five', artist: ['Dave Brubeck Quartet'], genres: ['Jazz'], duration: '5:24' },
    { name: 'Strobe', artist: ['Deadmau5'], genres: ['Electronic'], duration: '10:37' },
    { name: 'Smells Like Teen Spirit', artist: ['Nirvana'], genres: ['Rock'], duration: '5:01' },
    { name: 'Ring of Fire', artist: ['Johnny Cash'], genres: ['Country'], duration: '2:37' },
    { name: 'Shape of You', artist: ['Ed Sheeran'], genres: ['Pop'], duration: '3:54' },
    { name: 'Sicko Mode', artist: ['Travis Scott'], genres: ['Hip-Hop'], duration: '5:12' },
    { name: 'What a Wonderful World', artist: ['Louis Armstrong'], genres: ['Jazz'], duration: '2:21' },
    { name: 'Animals', artist: ['Martin Garrix'], genres: ['Electronic'], duration: '5:03' },
    { name: 'Hotel California', artist: ['Eagles'], genres: ['Rock'], duration: '6:30' },
    { name: 'Take Me Home, Country Roads', artist: ['John Denver'], genres: ['Country'], duration: '3:10' },
    { name: 'Thriller', artist: ['Michael Jackson'], genres: ['Pop'], duration: '5:57' },
    { name: 'Gods Plan', artist: ['Drake'], genres: ['Hip-Hop'], duration: '3:18' },
    { name: 'Blue in Green', artist: ['Miles Davis'], genres: ['Jazz'], duration: '5:37' },
    { name: 'Ghosts N Stuff', artist: ['Deadmau5', 'Rob Swire'], genres: ['Electronic'], duration: '5:28' },
    { name: 'Highway to Hell', artist: ['AC/DC'], genres: ['Rock'], duration: '3:28' },
    { name: 'Before He Cheats', artist: ['Carrie Underwood'], genres: ['Country'], duration: '3:19' },
    { name: 'Uptown Funk', artist: ['Mark Ronson', 'Bruno Mars'], genres: ['Pop', 'Funk'], duration: '4:30' },
    { name: 'Stronger', artist: ['Kanye West'], genres: ['Hip-Hop'], duration: '5:11' },
    { name: 'All of Me', artist: ['John Legend'], genres: ['R&B'], duration: '4:30' },
    { name: 'So What', artist: ['Miles Davis'], genres: ['Jazz'], duration: '9:22' },
    { name: 'Levels', artist: ['Avicii'], genres: ['Electronic'], duration: '5:39' },
    { name: 'Come Together', artist: ['The Beatles'], genres: ['Rock'], duration: '4:19' },
    { name: 'The Gambler', artist: ['Kenny Rogers'], genres: ['Country'], duration: '3:32' },
    { name: 'Someone Like You', artist: ['Adele'], genres: ['Pop'], duration: '4:45' },
    { name: 'C.R.E.A.M.', artist: ['Wu-Tang Clan'], genres: ['Hip-Hop'], duration: '4:12' },
    { name: 'At Last', artist: ['Etta James'], genres: ['R&B'], duration: '3:02' },
    { name: 'Fly Me to the Moon', artist: ['Frank Sinatra'], genres: ['Jazz'], duration: '2:27' },
    { name: 'Faded', artist: ['Alan Walker'], genres: ['Electronic'], duration: '3:32' },
    { name: 'Sweet Child O Mine', artist: ['Guns N Roses'], genres: ['Rock'], duration: '5:55' },
    { name: 'Friends in Low Places', artist: ['Garth Brooks'], genres: ['Country'], duration: '4:18' },
    { name: 'Firework', artist: ['Katy Perry'], genres: ['Pop'], duration: '3:48' },
    { name: 'Juicy', artist: ['The Notorious B.I.G.'], genres: ['Hip-Hop'], duration: '5:02' },
    { name: 'End of the Road', artist: ['Boyz II Men'], genres: ['R&B'], duration: '5:50' },
    { name: 'Round Midnight', artist: ['Thelonious Monk'], genres: ['Jazz'], duration: '5:55' },
    { name: 'Titanium', artist: ['David Guetta', 'Sia'], genres: ['Electronic'], duration: '4:05' },
    { name: 'Enter Sandman', artist: ['Metallica'], genres: ['Rock'], duration: '5:31' },
    { name: 'Chicken Fried', artist: ['Zac Brown Band'], genres: ['Country'], duration: '3:58' },
    { name: 'Rolling in the Deep', artist: ['Adele'], genres: ['Pop'], duration: '3:48' },
    { name: 'Empire State of Mind', artist: ['Jay-Z', 'Alicia Keys'], genres: ['Hip-Hop'], duration: '4:36' },
    { name: 'No Scrubs', artist: ['TLC'], genres: ['R&B'], duration: '3:34' },
    { name: 'Misty', artist: ['Erroll Garner'], genres: ['Jazz'], duration: '2:50' },
    { name: 'Sandstorm', artist: ['Darude'], genres: ['Electronic'], duration: '3:46' },
    { name: 'Back in Black', artist: ['AC/DC'], genres: ['Rock'], duration: '4:15' },
    { name: 'Take This Job and Shove It', artist: ['Johnny Paycheck'], genres: ['Country'], duration: '2:40' },
    { name: 'Halo', artist: ['Beyoncé'], genres: ['Pop', 'R&B'], duration: '4:21' },
    { name: 'HUMBLE.', artist: ['Kendrick Lamar'], genres: ['Hip-Hop'], duration: '2:57' },
    { name: 'Un-break My Heart', artist: ['Toni Braxton'], genres: ['R&B'], duration: '4:32' },
    { name: 'Autumn Leaves', artist: ['Cannonball Adderley'], genres: ['Jazz'], duration: '11:00' },
    { name: 'Scary Monsters and Nice Sprites', artist: ['Skrillex'], genres: ['Electronic'], duration: '4:03' }
];

export default songs;